### ISSUE TITLE
Add pre-commit to the supported packages

### ISSUE THREAD

**Issue by ethiy** [upciti/ops2deb#180]
This issue has as objective to add the `pre-commit` tool in the ops2deb registery.

The files could be downloaded from [PYPI](https://pypi.org/project/pre-commit/#files).

**Comment by fyhertz** [comment]
What do you mean? What is the ops2deb registery?

**Comment by ethiy** [comment]
@fyhertz 
I I understand well [how `wakemeops` works](https://github.com/upciti/wakemeops#monocle_face-how-does-it-work), to add `pre-commit`, one needs to make a debian package first in ops2deb before adding it to wakemeops.

Did I understand well how `wakemeops` packages can be added?
