### ISSUE TITLE
Bad project version "0"

### ISSUE THREAD

**Issue by windowsboy111** [upciti/ops2deb#370]
If you look into [`pyproject.toml`](https://github.com/upciti/ops2deb/blob/main/pyproject.toml#L3) you'll see
```toml
version = "0"
```
which prevents `ops2deb` from being packaged properly as a Python project as `poetry build` generates a wheel with version 0.

I'd suggest changing it to the correct version `2.4.1` (as of writing).

**Comment by fyhertz** [comment]
The version is set using `poetry version` in the ci.
